name: highcap_ci
channels:
- conda-forge
- defaults
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- pyyaml
- geopandas
- numpy
- scipy
- pandas
- gdal
- fiona
- rasterio>=1.0
- rasterstats
- shapely
- rtree
- pyproj>=2.0
- pyshp
- xlrd
- openpyxl
- requests
- pytest
- flake8
- codecov
- coverage