name: highcap_ci
channels:
- conda-forge
- defaults
dependencies:
- python
- matplotlib
- pyyaml
- numpy
- scipy
- pandas
- xlrd
- openpyxl
- requests
- pytest
- flake8
- codecov
- coverage
- geopandas
- pyproj
