name: hicap_ci
channels:
- conda-forge
- defaults
dependencies:
- python
- matplotlib
- pyyaml
- numpy
- scipy
- pandas
- xlrd
- openpyxl
- requests
- pytest
- flake8
- codecov
- coverage
- geopandas
- pyproj
- sphinx
- numpydoc
- nbsphinx  # for rendering notebooks in sphinx-generated docs
- sphinx-copybutton
- sphinx_rtd_theme
